version: '3'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - server-go

  server-go:
    build: ./server-go
    ports:
      - "8080:8080"
    volumes:
      - ./server-go:/app
    depends_on:
      - agent-py

  agent-py:
    build: ./agent-py
    ports:
      - "8000:8000"
    volumes:
      - ./agent-py:/app
